# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roombook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomreservation',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roombook.Event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='room_reservation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp', to='roombook.RoomReservation'),
        ),
    ]
