# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 15:56
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import Case, Value, When


def swap_training_and_interview(apps, schema_editor):
    Event = apps.get_model('roombook', 'Event')
    Event.objects.update(
        category=Case(
            When(category='training', then=Value('interview')),
            When(category='interview', then=Value('training')),
            default=Value('meeting')
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        ('roombook', '0004_remove_event_room_reservation'),
    ]

    operations = [
        migrations.RunPython(swap_training_and_interview, swap_training_and_interview)
    ]
