# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 14:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roombook', '0003_auto_20171017_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='room_reservation',
        ),
    ]
